### ISSUE TITLE
Chicago Manual Presentation issues

### ISSUE THREAD

**Issue by adam3smith** [citation-style-language/styles#3243]
https://github.com/jgm/pandoc-citeproc/issues/45
and 
https://forums.zotero.org/discussion/69698/style-error-chicago-fullnote-bibliography-csl-presentation-does-not-output-type#latest

**Comment by njbart** [comment]
@adam3smith – In https://github.com/jgm/pandoc-citeproc/issues/45#issuecomment-355379588 you said, “Chicago has so many moving parts that it always takes a bit longer to fix, but shouldn't be too hard here.” – Your work’s much appreciated, and I have no complaints at all about having to wait some time …

… but I do have my doubts whether the new stale bot indiscriminately closing issues after 30 days of inactivity is such a good idea – it seems to kind of defeat the actual purpose of an issue tracker.

**Comment by njbart** [comment]
Great this is being dealt with. However, it seems that with the latest fixes to chicago-fullnote-bibliography.csl, `event` and `event-place` are omitted from the notes (they used to be included previously; see https://github.com/jgm/pandoc-citeproc/issues/45#issue-34230655).

CMOS (17e, 14.217) quite clearly does call for including this information in notes:

> 1. David G. Harper, “The Several Discoveries of the Ciliary Muscle” (Power­Point presentation, 25th Anniversary of the Cogan Ophthalmic History Society, Bethesda, MD, March 31,2012).

> 2. Viviana Hong, “Censorship in Children’s Literature during Argentina’s Dirty War (1976-1983)” (lecture, University of Chicago, Chicago, IL, April 30, 2015).

pandoc example (same as in https://github.com/jgm/pandoc-citeproc/issues/45#issue-34230655):

```
pandoc -s -F pandoc-citeproc -t plain <<EOT

Foo [@item1]. Bar [@item2].

# References {-}

---
csl: chicago-fullnote-bibliography.csl
references:
- title-short: Early violent death in delinquent youth
  author:
  - family: Teplin
    given: Linda A.
  - family: McClelland
    given: Gary M.
  - family: Abram
    given: Karen M.
  - family: Washburn
    given: Jason J.
  id: item2
  issued:
    date-parts:
    - - 2005
      - 3
  title: 'Early violent death in delinquent youth: A prospective longitudinal study'
  type: speech
  genre: paper
  event: Annual Meeting of the American Psychology-Law Society
  event-place: La Jolla, CA

- author:
  - family: "D’Erasmo"
    given: Stacy
  id: item1
  issued:
    date-parts:
    - - 2000
      - 4
      - 26
  title: The craft and career of writing
  type: speech
  genre: lecture
  event-place: Northwestern University, Evanston, IL
...
EOT
```

Actual output (with the latest chicago-fullnote-bibliography.csl):

```
Foo.[1] Bar.[2]

References

D’Erasmo, Stacy. “The Craft and Career of Writing.” Lecture,
Northwestern University, Evanston, IL, April 26, 2000.

Teplin, Linda A., Gary M. McClelland, Karen M. Abram, and Jason J.
Washburn. “Early Violent Death in Delinquent Youth: A Prospective
Longitudinal Study.” Paper presented at the Annual Meeting of the
American Psychology-Law Society, La Jolla, CA, March 2005.

[1] Stacy D’Erasmo, “The Craft and Career of Writing” (lecture, April
26, 2000).

[2] Linda A. Teplin et al., “Early Violent Death in Delinquent Youth: A
Prospective Longitudinal Study” (paper, March 2005).
```

Expected output (just the notes):

```
[^1]: Stacy D’Erasmo, “The Craft and Career of Writing” (lecture,
    Northwestern University, Evanston, IL, April 26, 2000).

[^2]: Linda A. Teplin et al., “Early Violent Death in Delinquent Youth:
    A Prospective Longitudinal Study” (paper presented at the Annual
    Meeting of the American Psychology-Law Society, La Jolla, CA, March
    2005).
```
