### ISSUE TITLE
Chicago styles need to improve original-date and circa

### ISSUE THREAD

**Issue by reagle** [citation-style-language/styles#4262]
As discussed on the pandoc list:

- chicago-fullnote-bibliography.csl doesn't use origdate. [1](https://groups.google.com/d/msg/pandoc-discuss/fviK2lhiAU0/mGmjcykrAQAJ)
- chicago-fullnote-bibliography.csl confuses “circa” with “uncertain” [2](https://groups.google.com/d/msg/pandoc-discuss/fviK2lhiAU0/aGPtVtWlAQAJ)
- chicago-author-date.csl renders nothing w.r.t. to “circa”. [3](https://groups.google.com/d/msg/pandoc-discuss/fviK2lhiAU0/aGPtVtWlAQAJ)

**Comment by adam3smith** [comment]
1. I get output (as "Reprint") for chicago-fullnote-bibliography.csl. Does that not work with pandoc? Have you tried with Zotero?
2. As Nick points out later in that discussion, CSL doesn't distinguish between ca. and uncertain (and neither does Chicago Manual) so we can't fix this within current CSL and it's unclear if it needs fixing at all.
3. We can fix.

**Comment by reagle** [comment]
On issue #1, yes, my apologies, I see "repr. ...".

```
<li id="fn1" role="doc-endnote"><p>Marcus Aurelius, <em>Meditations</em>, ed. Maxwell Staniforth (161AD–180AD; repr., London: Penguin Books, 2005).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
```

**Comment by reagle** [comment]
On point 2 (circa) I don't think it is working for pandoc and chicago-fullnote-bibliography.csl.

```
---
author: Joseph Reagle 
title: "Test"
suppress-bibliography: true
...

test of [@Aurelius2005mns]

---
references:
- id: Aurelius2005mns
  type: book
  publisher-place: "London"
  author:
  - family: "Aurelius"
    given: "Marcus"
  issued:
  - year: 2005
  original-date:
    - year: 180
      circa: true
  editor:
  - family: "Staniforth"
    given: "Maxwell"
  ISBN: "9780143036272"
  publisher: "Penguin Books"
  title: "Meditations"
...
```
yields
```
╰─➤  pandoc -f markdown+yaml_metadata_block -w html --csl=chicago-fullnote-bibliography.csl --filter pandoc-citeproc test.md
<p>test of<span class="citation" data-cites="Aurelius2005mns"><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></span></p>
<section class="footnotes" role="doc-endnotes">
<hr />
<ol>
<li id="fn1" role="doc-endnote"><p>Marcus Aurelius, <em>Meditations</em>, ed. Maxwell Staniforth (180AD; repr., London: Penguin Books, 2005).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>
```
